import { Suspense, useMemo, useRef } from 'react'
import type { PointerEvent, RefObject } from 'react'
import * as THREE from 'three'
import { Canvas, useFrame } from '@react-three/fiber'
import { Float, useGLTF } from '@react-three/drei'
import { useInView } from '../lib/useInView'
import { useReducedMotion } from '../lib/useReducedMotion'
import styles from './MarkCanvas.module.css'
import { cssColor } from './palette'
import { haloShader } from './shaders'
import { input } from './state'

const MODEL = '/models/mark.glb'
const ACCENT = cssColor('--accent')
/** Radians of spin per pixel dragged. */
const DRAG = 0.012
/** Seconds between the halos lighting up around the triangle, and how long each one glows. */
const PING_STEP = 0.14
const PING_GLOW = 0.9
const { damp } = THREE.MathUtils

interface Spin {
  angle: number
  velocity: number
  dragging: boolean
  x: number
  time: number
  downX: number
  downY: number
  /** performance.now() of the last ping. */
  ping: number
}

/**
 * The brand mark, loaded from the GLB asset generated by scripts/build-mark.mjs.
 * Drag spins it (with inertia); a click sends a ping around the triangle.
 */
function Mark({ animate, spinRef }: { animate: boolean; spinRef: RefObject<Spin> }) {
  const { scene } = useGLTF(MODEL)
  const g = useRef<THREE.Group>(null)
  const halos = useRef<Array<THREE.Mesh | null>>([])
  // Halo positions come from the GLB's own nodes so they always sit on the spheres.
  const nodes = useMemo(
    () =>
      ['node-0', 'node-1', 'node-2'].map(
        (name) => scene.getObjectByName(name)?.position.clone() ?? new THREE.Vector3(),
      ),
    [scene],
  )
  const haloUniforms = useMemo(
    () => nodes.map(() => ({ uColor: { value: new THREE.Color(ACCENT) }, uOpacity: { value: 0 } })),
    [nodes],
  )

  useFrame((state, delta) => {
    if (!g.current || !animate) return
    const s = spinRef.current
    const dt = Math.min(delta, 0.1)
    const t = state.clock.elapsedTime
    if (!s.dragging) {
      s.angle += s.velocity * dt
      s.velocity = damp(s.velocity, 0, 1.5, dt)
    }
    const ty = state.pointer.x * 0.6 + Math.sin(t * 0.4) * 0.35 + s.angle
    const tx = -state.pointer.y * 0.3
    g.current.rotation.y = damp(g.current.rotation.y, ty, s.dragging ? 14 : 3, delta)
    g.current.rotation.x = damp(g.current.rotation.x, tx, 3, delta)

    // Ping: each node's halo swells and fades, one after another around the triangle.
    const age = (performance.now() - s.ping) / 1000
    halos.current.forEach((halo, i) => {
      if (!halo) return
      const k = (age - i * PING_STEP) / PING_GLOW
      const on = k > 0 && k < 1
      halo.visible = on
      if (!on) return
      halo.scale.setScalar(1 + k * 1.4)
      ;(halo.material as THREE.ShaderMaterial).uniforms.uOpacity.value = Math.sin(Math.PI * k)
    })
  })

  return (
    <group ref={g}>
      <primitive object={scene} />
      {nodes.map((p, i) => (
        <mesh
          key={i}
          ref={(m) => {
            halos.current[i] = m
          }}
          position={p}
          visible={false}
        >
          <sphereGeometry args={[0.22, 32, 24]} />
          <shaderMaterial
            vertexShader={haloShader.vertexShader}
            fragmentShader={haloShader.fragmentShader}
            uniforms={haloUniforms[i]}
            transparent
            depthWrite={false}
            blending={THREE.AdditiveBlending}
          />
        </mesh>
      ))}
    </group>
  )
}

export default function MarkCanvas() {
  const reduced = useReducedMotion()
  const wrap = useRef<HTMLDivElement>(null)
  const inView = useInView(wrap)
  const frameloop: 'always' | 'demand' | 'never' = reduced ? 'demand' : inView ? 'always' : 'never'
  const spinRef = useRef<Spin>({
    angle: 0,
    velocity: 0,
    dragging: false,
    x: 0,
    time: 0,
    downX: 0,
    downY: 0,
    ping: -1e9,
  })

  const onPointerDown = (e: PointerEvent<HTMLDivElement>) => {
    if (reduced || e.button !== 0) return
    const s = spinRef.current
    s.dragging = true
    s.x = s.downX = e.clientX
    s.downY = e.clientY
    s.time = e.timeStamp
    s.velocity = 0
    e.currentTarget.setPointerCapture(e.pointerId)
  }
  const onPointerMove = (e: PointerEvent<HTMLDivElement>) => {
    const s = spinRef.current
    if (!s.dragging) return
    const turn = (e.clientX - s.x) * DRAG
    s.angle += turn
    s.velocity = turn / Math.max(0.008, (e.timeStamp - s.time) / 1000)
    s.x = e.clientX
    s.time = e.timeStamp
  }
  const onPointerUp = (e: PointerEvent<HTMLDivElement>) => {
    const s = spinRef.current
    if (!s.dragging) return
    s.dragging = false
    // A click rather than a drag: ping the mark, give it a flick, and send a signal
    // through the network behind the card.
    if (Math.hypot(e.clientX - s.downX, e.clientY - s.downY) < 6) {
      s.ping = performance.now()
      s.velocity += 5
      input.pings++
    }
  }

  return (
    <div
      ref={wrap}
      className={styles.canvas}
      aria-hidden="true"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerCancel={() => {
        spinRef.current.dragging = false
      }}
    >
      <Canvas
        dpr={[1, 1.5]}
        frameloop={frameloop}
        camera={{ position: [0, 0, 3.4], fov: 35 }}
        gl={{ antialias: true, alpha: true }}
        onCreated={({ gl }) => gl.setClearColor(0x000000, 0)}
      >
        <ambientLight intensity={0.5} />
        <directionalLight position={[2, 3, 4]} intensity={2} />
        <pointLight position={[-2, -1, 2]} intensity={5} color={cssColor('--glow')} distance={8} />
        <Suspense fallback={null}>
          <Float
            speed={reduced ? 0 : 1.6}
            rotationIntensity={reduced ? 0 : 0.5}
            floatIntensity={reduced ? 0 : 0.9}
          >
            <Mark animate={!reduced} spinRef={spinRef} />
          </Float>
        </Suspense>
      </Canvas>
    </div>
  )
}

useGLTF.preload(MODEL)
