import { Suspense, useRef } from 'react'
import * as THREE from 'three'
import { Canvas, useFrame } from '@react-three/fiber'
import { Float, useGLTF } from '@react-three/drei'
import { useInView } from '../lib/useInView'
import { useReducedMotion } from '../lib/useReducedMotion'
import styles from './MarkCanvas.module.css'
import { cssColor } from './palette'

const MODEL = '/models/mark.glb'
const { damp } = THREE.MathUtils

/** The brand mark, loaded from the GLB asset generated by scripts/build-mark.mjs. */
function Mark({ animate }: { animate: boolean }) {
  const { scene } = useGLTF(MODEL)
  const g = useRef<THREE.Group>(null)

  useFrame((state, delta) => {
    if (!g.current || !animate) return
    const t = state.clock.elapsedTime
    const ty = state.pointer.x * 0.6 + Math.sin(t * 0.4) * 0.35
    const tx = -state.pointer.y * 0.3
    g.current.rotation.y = damp(g.current.rotation.y, ty, 3, delta)
    g.current.rotation.x = damp(g.current.rotation.x, tx, 3, delta)
  })

  return (
    <group ref={g}>
      <primitive object={scene} />
    </group>
  )
}

export default function MarkCanvas() {
  const reduced = useReducedMotion()
  const wrap = useRef<HTMLDivElement>(null)
  const inView = useInView(wrap)
  const frameloop: 'always' | 'demand' | 'never' = reduced ? 'demand' : inView ? 'always' : 'never'

  return (
    <div ref={wrap} className={styles.canvas} aria-hidden="true">
      <Canvas
        dpr={[1, 1.5]}
        frameloop={frameloop}
        camera={{ position: [0, 0, 3.4], fov: 35 }}
        gl={{ antialias: true, alpha: true }}
        onCreated={({ gl }) => gl.setClearColor(0x000000, 0)}
      >
        <ambientLight intensity={0.5} />
        <directionalLight position={[2, 3, 4]} intensity={2} />
        <pointLight position={[-2, -1, 2]} intensity={5} color={cssColor('--glow')} distance={8} />
        <Suspense fallback={null}>
          <Float
            speed={reduced ? 0 : 1.6}
            rotationIntensity={reduced ? 0 : 0.5}
            floatIntensity={reduced ? 0 : 0.9}
          >
            <Mark animate={!reduced} />
          </Float>
        </Suspense>
      </Canvas>
    </div>
  )
}

useGLTF.preload(MODEL)
